### ISSUE TITLE
oculus file formats

### ISSUE THREAD

**Issue by greenpau** [dignifiedweb/OculusHomeIconChanger#6]
@dignifiedweb , thank you for your work and this repo! 👍 

 I am doing a research on the layout of manifests and other files in Oculus app.

I did not compile this app yet. However, it looks like you are regenerating the `*_assets.json` (which likely point to `C:\Program Files\Oculus\CoreData\Software\StoreAssets`). Maybe I am wrong.

Do you know if there is a doc describing various formats used in `C:\Program Files\Oculus\Software\Manifests` and in `C:\Program Files\Oculus\CoreData\Manifests`.

**Comment by dignifiedweb** [comment]
No problem. 

I am not aware of a document that Meta/Oculus has made for manifest files. I just know there's basically 2 types, the hake and the media manifest files. Media meaning images for game and game meaning the exe. Someone contributed to my repo for the "add new" button that just calls a powershell script. I didn't have time to redo I'm c# code but it works well and appreciated the help. 

That poweshell is here:
https://github.com/dignifiedweb/OculusHomeIconChanger/blob/master/OculusHomeIconChanger/AddtoOculus.ps1

That details the exact requirements for creating a new file and where they are located. I think you were right with location. Hope that helps!

**Comment by greenpau** [comment]
Thank you for the pointer @dignifiedweb !
